# Generated by Django 4.1.4 on 2023-03-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='cat_catrgory',
            new_name='cat_category',
        ),
    ]
