# Generated by Django 4.1.4 on 2023-01-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
