# Generated by Django 4.1.4 on 2023-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forum_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date of publication'),
        ),
    ]
