# Generated by Django 4.1.4 on 2023-01-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoavatar',
            old_name='user',
            new_name='user_id',
        ),
    ]
