# Generated by Django 4.1.4 on 2023-01-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_user_photoavatar_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoavatar',
            old_name='user_id',
            new_name='user',
        ),
    ]
