# Generated by Django 4.1.4 on 2023-01-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfoliocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Counter'),
        ),
    ]
